config/routes.rb
Rails.application.routes.draw do
  root "flights#index"

  resources :flights, only: :index
  resources :bookings, only: %i[ new create show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: "Flight", foreign_key: :departure_airport_id
  has_many :arriving_flights, class_name: "Flight", foreign_key: :arrival_airport_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  has_many :bookings

  def self.available_dates
    # Self reminder: passing a symbol to ::order doesn't work when a string is passed to ::select
    select("date_trunc('day', date) AS date").distinct.order("date")
  end

  def pretty_date
    date.strftime("%d/%m/%Y")
  end

  def pretty_format
    ERB::Util.html_escape_once(
      "#{departure_airport.code} &rArr; #{arrival_airport.code}, departing at #{date.to_fs(:time)}"
    )
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new(flight_id: params[:flight_id])

    params[:number_of_passengers].to_i.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      redirect_to @booking
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.expect(booking: [ :flight_id, passengers_attributes: [ [ :name, :email ] ] ])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_codes_options = Airport.pluck(:code)
    @available_dates = Flight.available_dates

    if search_sent?
      @flights = Flight.order(:date).where(
        departure_airport: Airport.find_by(code: params[:departure_code]),
        arrival_airport: Airport.find_by(code: params[:arrival_code]),
        date: params[:date].to_date.all_day
      )

      @number_of_passengers = params[:number_of_passengers]
    end
  end

  private

  def search_sent?
    %i[departure_code arrival_code date number_of_passengers].all? { |necessary_key| params.has_key?(necessary_key) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= form_with model: @booking do |f| %>
  <%= render @booking.flight, inside_form: true %>

  <fieldset
    data-controller="fieldset"
    data-fieldset-minimum-value="1"
    data-fieldset-maximum-value="4"
  >
    <legend>Passengers</legend>

    <ol data-fieldset-target="fields">
      <%= render "passengers/fields", form: f, passenger: nil, fields_options: nil %>
    </ol>

    <template data-fieldset-target="template">
      <%# 'child_index' is an odd option as it isn't documented on the API %>
      <%= render "passengers/fields", form: f, passenger: Passenger.new, fields_options: { child_index: ":index" } %>
    </template>

    <div>
      <button type="button" data-action="fieldset#add">Add passenger</button>
    </div>
  </fieldset>

  <%= f.hidden_field :flight_id %>

  <%= f.button "Make new booking" %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking</h1>

<p>
  <%= link_to "Home", root_path %>
</p>

<%= render @booking.flight, inside_form: false %>

<div class="details">
  <h2>Passenger Details</h2>

  <ol>
    <%= render @booking.passengers %>
  </ol>
</div>

app/views/flights/_flight.html.erb
<div class="<%= 'details' unless inside_form %>">
  <h2>Flight Details</h2>

  <p>Flight ID: <%= flight.id %></p>

  <p>Departure Airport: <%= flight.departure_airport.code %></p>

  <p>Arrival Airport: <%= flight.arrival_airport.code %></p>

  <p>Date: <%= flight.date.to_fs(:long) %></p>
</div>

app/views/flights/index.html.erb
<h1>Flight Booker</h1>

<p>
  <%= link_to "Home", root_path %>
</p>

<%= form_with url: flights_path, method: :get, class: "search-form" do |f| %>
  <%= f.label :departure_code do |text| %>
    <%= text %>
    <%= f.select :departure_code, options_for_select(@airport_codes_options), prompt: "Select the departure airport" %>
  <% end %>

  <%= f.label :arrival_code do |text| %>
    <%= text %>
    <%= f.select :arrival_code, options_for_select(@airport_codes_options), prompt: "Select the arrival airport" %>
  <% end %>

  <%= f.label :number_of_passengers do |text| %>
    <%= text %>
    <%= f.select :number_of_passengers, options_for_select(1..4), prompt: "Select the number of passengers" %>
  <% end %>

  <%= f.label :date do |text| %>
    <%= text %>
    <%= f.collection_select :date, @available_dates, :date, :pretty_date, prompt: "Select an available date" %>
  <% end %>

  <%= f.button "Search flights" %>
<% end %>

<% if @flights&.any? %>
  <%= form_with url: new_booking_path, method: :get, class: "choose-flight-form" do |f| %>
    <%= f.hidden_field :number_of_passengers, value: @number_of_passengers %>

    <fieldset>
      <legend>Choose your flight</legend>

      <%= f.collection_radio_buttons :flight_id, @flights, :id, :pretty_format do |b| %>
        <%= b.label do %>
          <%= b.radio_button %>
          <%= b.text %>
        <% end %>
      <% end %>
    </fieldset>

    <%= f.button "Select Flight" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Flight Booker Odin" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Flight Booker Odin">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/passengers/_fields.html.erb
<%= form.fields_for :passengers, passenger, fields_options do |passenger_fields| %>
  <li>
    <%= passenger_fields.label :name do |text| %>
      <%= text %>
      <%= passenger_fields.text_field :name %>
    <% end %>

    <%= passenger_fields.label :email do |text| %>
      <%= text %>
      <%= passenger_fields.email_field :email %>
    <% end %>

    <button data-action="fieldset#remove" type="button">Remove passenger</button>
  </li>
<% end %>

app/views/passengers/_passenger.html.erb
<li>
  Name: <%= passenger.name %><br>
  Email: <%= passenger.email %>
</li>